### PR TITLE
QOL-8857 org template, update for 2.8 vs 2.9 formatting

### PR DESCRIPTION
**Pull request by duttonw**

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Comment by duttonw** [comment]
Any idea why it failed?

**Comment by ThrawnCA** [comment]
> Any idea why it failed?

Bad syntax on line 16.

**Review by ThrawnCA — APPROVED** [review]

**Comment by ThrawnCA** [comment]
ckanext-dcat has changed: https://github.com/ckan/ckanext-dcat/commit/6516d3373a8eda1db7d34f61696a989b9b2d93ca split the requirements files for Python 2 and 3. We need to install the py2 file.

**Comment by duttonw** [comment]
we should use v1.1.3 as it was working till v1.2.0 was released 6 days ago.

**Comment by ThrawnCA** [comment]
> we should use v1.1.3 as it was working till v1.2.0 was released 6 days ago.

Infrastructure uses v0.0.9 at present, https://github.com/qld-gov-au/ckan-qld-infrastructure/blob/a495f576bed24ec62bad6fd6c487d7ce35a8469e/vars/shared-OpenData.var.yml#L50

**Comment by duttonw** [comment]
> > we should use v1.1.3 as it was working till v1.2.0 was released 6 days ago.
> 
> Infrastructure uses v0.0.9 at present, https://github.com/qld-gov-au/ckan-qld-infrastructure/blob/a495f576bed24ec62bad6fd6c487d7ce35a8469e/vars/shared-OpenData.var.yml#L50

true, but we were using 'master' till it broke, we should bump to v1.1.3 on deployment as it might actually be at the version without us knowing due to how the plugin's get installed.

**Pull request merged**
